spring:
    application:
        name: security-app 
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: mysecretpassword
    jpa:
        hibernate:
            ddl-auto: none