spring:
    application:
        name: security-app 
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: mysecretpassword
    jpa:
        hibernate:
            ddl-auto: none
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone: Asia/Jakarta
        property-naming-strategy: KEBAB_CASE
        default-property-inclusion: always
